### ISSUE TITLE
Code Coverage Configuration

### ISSUE THREAD

**Issue by Chafficui** [ChafficPlugins/ChafficLib#4]
### Description
Set up code coverage reporting with JaCoCo and Codecov integration.

### Tasks
- [x] Configure JaCoCo plugin
- [x] Set up coverage thresholds
- [x] Configure Codecov integration
- [x] Set up coverage reports
- [x] Configure coverage verification
- [x] Add coverage badges

### Acceptance Criteria
- Coverage reports are generated
- Coverage verification enforces 80% minimum
- Codecov integration works
- Coverage badges are displayed in README
